### ISSUE TITLE
Need bazaar to install

### ISSUE THREAD

**Issue by assertnotnull** [gengo/goship#197]
Trying to install but requires bazaar. Can it be avoided? I have no other projects requiring this.

```
go get github.com/gengo/goship
go: missing Bazaar command. See https://golang.org/s/gogetcmd
package labix.org/v2/mgo/bson: exec: "bzr": executable file not found in $PATH
```

**Comment by spankie** [comment]
if you are on debian based linux install `bzr` with the following command `sudo apt-get install bzr`
